const QB = QUESTION_BANK;
const K={r:'fitter_practice_records',w:'fitter_wrong_questions',s:'fitter_settings'};
let CQ=[],UA={},CI=0,ST=0,TI=null,CAT=new Set(),MODE='practice',ANSWER_SHOWN={};
function init(){popCat();popBankCat();upStat();loadS();setTabs();setEvents();renRec();renW();renBank();}
function popCat(){const cs=document.getElementById('question-category');['single','multi','judge','short','calc'].forEach(t=>{if(QB[t])QB[t].forEach(q=>{if(q.category)CAT.add(q.category);});});Array.from(CAT).sort().forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;cs.appendChild(o);});}
function popBankCat(){const bc=document.getElementById('bank-cat');Array.from(CAT).sort().forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;bc.appendChild(o);});}
function upStat(){const ts=['single','multi','judge','short','calc'];let tt=0;ts.forEach(t=>{const c=QB[t]?QB[t].length:0;document.getElementById('stat-'+t).textContent=c;tt+=c;});document.getElementById('stat-total').textContent=tt;document.getElementById('max-count').textContent=tt;document.getElementById('question-count').max=tt;document.getElementById('default-count').max=tt;}
function loadS(){try{const s=JSON.parse(localStorage.getItem(K.s)||'{}');if(s.defaultQuestionCount)document.getElementById('question-count').value=s.defaultQuestionCount;}catch(e){}}
function saveS(){const c=parseInt(document.getElementById('default-count').value)||10;localStorage.setItem(K.s,JSON.stringify({defaultQuestionCount:c}));document.getElementById('question-count').value=c;alert('设置已保存');}
function setTabs(){document.querySelectorAll('.tab-btn').forEach(b=>{b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tc').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('tab-'+b.dataset.tab).classList.add('active');});});}
function setEvents(){document.getElementById('start-btn').addEventListener('click',startP);document.getElementById('prev-btn').addEventListener('click',()=>{if(CI>0){CI--;showQ();}});document.getElementById('next-btn').addEventListener('click',nextQ);document.getElementById('submit-btn').addEventListener('click',requestSubmit);document.getElementById('restart-btn').addEventListener('click',showStart);document.getElementById('review-btn').addEventListener('click',showRev);document.getElementById('clear-records-btn').addEventListener('click',()=>{if(confirm('确定清除所有练习记录？')){localStorage.removeItem(K.r);renRec();}});document.getElementById('clear-wrong-btn').addEventListener('click',()=>{if(confirm('确定清空错题本？')){localStorage.removeItem(K.w);renW();}});document.getElementById('practice-wrong-btn').addEventListener('click',pracW);document.getElementById('save-settings-btn').addEventListener('click',saveS);document.getElementById('clear-all-btn').addEventListener('click',()=>{if(confirm('确定清除所有数据？此操作不可恢复！')){Object.values(K).forEach(k=>localStorage.removeItem(k));renRec();renW();}});document.getElementById('install-help-btn').addEventListener('click',showInstallGuide);document.getElementById('bank-type').addEventListener('change',()=>{bankPage=0;renBank();});document.getElementById('bank-cat').addEventListener('change',()=>{bankPage=0;renBank();});document.getElementById('bank-search').addEventListener('input',()=>{bankPage=0;renBank();});document.getElementById('bank-prev').addEventListener('click',()=>{if(bankPage>0){bankPage--;renBank();}});document.getElementById('bank-next').addEventListener('click',()=>{bankPage++;renBank();});}
function getPool(){const tp=document.getElementById('question-type').value,ca=document.getElementById('question-category').value;let p=[];const ts=tp==='all'?['single','multi','judge','short','calc']:[tp];ts.forEach(t=>{if(QB[t])p=p.concat(QB[t]);});if(ca!=='all')p=p.filter(q=>q.category===ca);return p;}
function shuf(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
function calcS(n){if(n<=0)return[];const b=Math.round(100/n);const s=new Array(n-1).fill(b);s.push(100-b*(n-1));return s;}
function startP(){const p=getPool();const r=parseInt(document.getElementById('question-count').value)||10;const c=Math.min(r,p.length);if(c===0){alert('题库为空，请调整筛选条件');return;}MODE=document.getElementById('practice-mode').value;CQ=shuf(p).slice(0,c);CQ.forEach((q,i)=>q.score=calcS(c)[i]);UA={};ANSWER_SHOWN={};CI=0;ST=Date.now();document.getElementById('practice-start').classList.add('hi');document.getElementById('practice-area').classList.remove('hi');document.getElementById('result-area').classList.add('hi');document.getElementById('total-num').textContent=c;startT();showQ();}
function startT(){clearInterval(TI);TI=setInterval(()=>{const e=Math.floor((Date.now()-ST)/1000);const m=String(Math.floor(e/60)).padStart(2,'0');const s=String(e%60).padStart(2,'0');document.getElementById('timer').textContent=m+':'+s;},1000);}
function showStart(){document.getElementById('practice-start').classList.remove('hi');document.getElementById('practice-area').classList.add('hi');document.getElementById('result-area').classList.add('hi');clearInterval(TI);}
function showQ(){const q=CQ[CI];document.getElementById('current-num').textContent=CI+1;document.getElementById('submit-btn').style.display=MODE==='exam'?'inline-block':'none';document.getElementById('answer-panel').classList.toggle('hi',!ANSWER_SHOWN[q.id]);document.getElementById('progress-fill').style.width=((CI+1)/CQ.length*100)+'%';const tn=q.type==='single'?'单选':q.type==='multi'?'多选':q.type==='judge'?'判断':q.type==='short'?'简答':'计算';document.getElementById('question-meta').textContent='['+tn+'] '+(q.category||'')+' · 本题'+q.score+'分';document.getElementById('question-text').textContent=q.question;const oa=document.getElementById('options-area');const ta=document.getElementById('text-answer-area');oa.innerHTML='';ta.style.display='none';document.getElementById('prev-btn').disabled=CI===0;const nb=document.getElementById('next-btn');nb.textContent=CI===CQ.length-1?'提交':'下一题';if(q.type==='single'||q.type==='judge'){const os=q.type==='judge'?{'true':'正确','false':'错误'}:q.options;Object.entries(os).forEach(([k,v])=>{const l=document.createElement('label');l.className='ol';if(UA[q.id]===k)l.classList.add('sel');l.innerHTML='<input type="radio" name="opt" class="oi" value="'+k+'" '+(UA[q.id]===k?'checked':'')+'> <span>'+k+'. '+v+'</span>';l.querySelector('input').addEventListener('change',()=>{UA[q.id]=k;showQ();});oa.appendChild(l);});}else if(q.type==='multi'){const se=UA[q.id]||[];Object.entries(q.options).forEach(([k,v])=>{const l=document.createElement('label');l.className='ol';if(se.includes(k))l.classList.add('sel');l.innerHTML='<input type="checkbox" class="oi" value="'+k+'" '+(se.includes(k)?'checked':'')+'> <span>'+k+'. '+v+'</span>';l.querySelector('input').addEventListener('change',(e)=>{let a=UA[q.id]||[];if(e.target.checked)a.push(k);else a=a.filter(x=>x!==k);UA[q.id]=a;showQ();});oa.appendChild(l);});}else{ta.style.display='block';document.getElementById('text-answer').value=UA[q.id]||'';document.getElementById('text-answer').oninput=(e)=>{UA[q.id]=e.target.value;};}}
function nextQ(){const q=CQ[CI];if(MODE==='practice'&&!ANSWER_SHOWN[q.id]){if(checkA(q,UA[q.id])){if(CI<CQ.length-1){CI++;showQ();}else{showCurrentAnswer();}}else{showCurrentAnswer();}return;}if(CI<CQ.length-1){CI++;showQ();}else if(MODE==='exam'){requestSubmit();}}
function answerText(q){if(q.type==='single')return '正确答案：'+q.answer+'<br>'+Object.entries(q.options||{}).map(([k,v])=>k+'. '+v).join('<br>');if(q.type==='multi')return '正确答案：'+q.answer.join('')+'<br>'+Object.entries(q.options||{}).map(([k,v])=>k+'. '+v).join('<br>');if(q.type==='judge')return '正确答案：'+(q.answer?'正确（√）':'错误（×）');return '参考答案：'+q.answer;}
function showCurrentAnswer(){const q=CQ[CI];ANSWER_SHOWN[q.id]=true;const p=document.getElementById('answer-panel');p.innerHTML='<b>答案</b><div class="sm mt1">'+answerText(q)+'</div>';p.classList.remove('hi');}
function requestSubmit(){const unanswered=CQ.filter(q=>{const a=UA[q.id];return !a||(Array.isArray(a)&&a.length===0);}).length;if(unanswered>0&&!confirm('还剩'+unanswered+'题未作答，是否提交答案，提交后无法撤回'))return;subP();}
function checkA(q,a){if(!a&&a!==false&&a!=='')return false;if(q.type==='single')return a===q.answer;if(q.type==='judge')return String(a)===String(q.answer);if(q.type==='multi'){const x=Array.isArray(a)?[...a].sort().join(''):String(a);const y=[...q.answer].sort().join('');return x===y;}if(!a)return false;const u=String(a).toLowerCase();return q.keywords.every(k=>u.includes(k.toLowerCase()));}
function subP(){clearInterval(TI);const el=Math.floor((Date.now()-ST)/1000);let ts=0,cc=0;const rs=[];CQ.forEach(q=>{const a=UA[q.id];const co=checkA(q,a);const sc=co?q.score:0;ts+=sc;if(co)cc++;rs.push({q,a,co,sc});if(!co)saveW(q,a);});saveRec({date:new Date().toISOString(),duration:el,score:ts,totalQuestions:CQ.length,correctCount:cc,wrongCount:CQ.length-cc,questions:CQ.map(q=>({...q})),userAnswers:{...UA},results:rs});showRes(ts,el,cc,rs);}
function showRes(ts,el,cc,rs){document.getElementById('practice-area').classList.add('hi');document.getElementById('result-area').classList.remove('hi');document.getElementById('final-score').textContent=ts+'分';document.getElementById('final-score').className='sb2 '+(ts>=60?'sp':'sf');const m=String(Math.floor(el/60)).padStart(2,'0');const s=String(el%60).padStart(2,'0');document.getElementById('final-time').textContent=m+':'+s;document.getElementById('final-correct').textContent=cc;document.getElementById('final-total').textContent=CQ.length;document.getElementById('final-rate').textContent=Math.round(cc/CQ.length*100)+'%';window._lr=rs;renW();}
function showRev(){const ar=document.getElementById('review-area');ar.innerHTML='';window._lr.forEach(r=>{const d=document.createElement('div');d.className='card rc '+(r.co?'':'wr');let ad='';if(r.q.type==='single')ad='你的答案：'+(r.a||'(未作答)')+' | 正确答案：'+r.q.answer;else if(r.q.type==='multi')ad='你的答案：'+(Array.isArray(r.a)?r.a.join(''):(r.a||'(未作答)'))+' | 正确答案：'+r.q.answer.join('');else if(r.q.type==='judge')ad='你的答案：'+(r.a==='true'?'正确':r.a==='false'?'错误':(r.a||'(未作答)'))+' | 正确答案：'+(r.q.answer?'正确':'错误');else ad='你的答案：'+(r.a||'(未作答)')+'<br>参考答案：'+r.q.answer;d.innerHTML='<div class="rs '+(r.co?'c':'w')+'">'+(r.co?'正确':'错误')+' ('+r.sc+'/'+r.q.score+'分)</div><div class="qt mt1">'+r.q.question+'</div><div class="sm mt1">'+ad+'</div>';ar.appendChild(d);});}
function saveRec(r){try{const rs=JSON.parse(localStorage.getItem(K.r)||'[]');rs.unshift(r);localStorage.setItem(K.r,JSON.stringify(rs));}catch(e){}renRec();}
function renRec(){const ls=document.getElementById('records-list');try{const rs=JSON.parse(localStorage.getItem(K.r)||'[]');if(rs.length===0){ls.innerHTML='<p class="ce tl mt2">暂无练习记录</p>';return;}ls.innerHTML='';rs.forEach((r,i)=>{const d=document.createElement('div');d.className='ri';const dt=new Date(r.date);const m=String(Math.floor(r.duration/60)).padStart(2,'0');const s=String(r.duration%60).padStart(2,'0');d.innerHTML='<div><div>'+dt.toLocaleString('zh-CN')+'</div><div class="sm tl">'+r.totalQuestions+'题 · '+r.score+'分 · '+r.correctCount+'对'+r.wrongCount+'错</div></div><div style="text-align:right"><div class="sv" style="font-size:1.2rem">'+r.score+'</div><div class="sm tl">'+m+':'+s+'</div></div>';d.addEventListener('click',()=>{const det=document.getElementById('rd-'+i);if(det)det.style.display=det.style.display==='block'?'none':'block';});ls.appendChild(d);const de=document.createElement('div');de.id='rd-'+i;de.className='rd';de.innerHTML=r.results.map(re=>'<div class="sm" style="margin:0.3rem 0"><b>'+(re.co?'✓':'✗')+'</b> '+re.q.question.substring(0,40)+'... ('+re.sc+'/'+re.q.score+'分)</div>').join('');ls.appendChild(de);});}catch(e){ls.innerHTML='<p class="ce tl mt2">暂无练习记录</p>';}}
function saveW(q,ua){try{const w=JSON.parse(localStorage.getItem(K.w)||'[]');const ex=w.find(x=>x.questionId===q.id);if(ex){ex.wrongCount++;ex.lastWrongDate=new Date().toISOString();ex.userAnswer=ua;}else{w.push({questionId:q.id,type:q.type,category:q.category||'',question:q.question,options:q.options||{},correctAnswer:q.answer,userAnswer:ua,wrongCount:1,lastWrongDate:new Date().toISOString()});}localStorage.setItem(K.w,JSON.stringify(w));}catch(e){}}
function renW(){const ls=document.getElementById('wrong-list');try{const w=JSON.parse(localStorage.getItem(K.w)||'[]');if(w.length===0){ls.innerHTML='<p class="ce tl mt2">暂无错题</p>';return;}w.sort((a,b)=>b.wrongCount-a.wrongCount);ls.innerHTML='';w.forEach(x=>{const d=document.createElement('div');d.className='wi';let at='';if(x.type==='single')at='正确答案：'+x.correctAnswer;else if(x.type==='multi')at='正确答案：'+x.correctAnswer.join('');else if(x.type==='judge')at='正确答案：'+(x.correctAnswer?'正确':'错误');else at='参考答案：'+x.correctAnswer;d.innerHTML='<div class="qt" style="font-size:0.95rem">'+x.question+'</div><div class="sm tl mt1">'+at+' · 累计答错'+x.wrongCount+'次 · '+x.category+'</div><div class="bg mt1"><button class="btn bd" onclick="rmW(&quot;'+x.questionId+'&quot;)">已掌握</button></div>';ls.appendChild(d);});}catch(e){ls.innerHTML='<p class="ce tl mt2">暂无错题</p>';}}
function rmW(qid){try{const w=JSON.parse(localStorage.getItem(K.w)||'[]');const f=w.filter(x=>x.questionId!==qid);localStorage.setItem(K.w,JSON.stringify(f));renW();}catch(e){}}
function pracW(){try{const w=JSON.parse(localStorage.getItem(K.w)||'[]');if(w.length===0){alert('错题本为空');return;}const pool=[];w.forEach(x=>{const all=[];['single','multi','judge','short','calc'].forEach(t=>{if(QB[t])all.push(...QB[t]);});const q=all.find(y=>y.id===x.questionId);if(q)pool.push(q);});if(pool.length===0){alert('错题数据异常');return;}const c=Math.min(parseInt(document.getElementById('question-count').value)||10,pool.length);CQ=shuf(pool).slice(0,c);CQ.forEach((q,i)=>q.score=calcS(c)[i]);UA={};CI=0;ST=Date.now();document.getElementById('practice-start').classList.add('hi');document.getElementById('practice-area').classList.remove('hi');document.getElementById('result-area').classList.add('hi');document.getElementById('total-num').textContent=c;startT();showQ();}catch(e){alert('错题练习出错');}}
function showInstallGuide(){const ua=navigator.userAgent.toLowerCase();const isIOS=/iphone|ipad|ipod/.test(ua);const isAndroid=/android/.test(ua);const isChrome=/chrome|crios/.test(ua);const isEdge=/edg/.test(ua);let html='';if(isIOS){html='<div class="wi"><div class="ct">iPhone / iPad Safari</div><ol class="sm" style="padding-left:1.2rem;line-height:1.9"><li>点击浏览器底部或顶部的“分享”按钮。</li><li>在菜单中找到“添加到主屏幕”。</li><li>名称建议填写“钳工练习”。</li><li>点击“添加”。</li></ol><p class="sm tl mt1">如果不是 Safari，建议先用 Safari 打开此 HTML 文件。</p></div>';}else if(isAndroid){html='<div class="wi"><div class="ct">Android 手机浏览器</div><ol class="sm" style="padding-left:1.2rem;line-height:1.9"><li>点击浏览器右上角“⋮”菜单。</li><li>选择“添加到主屏幕”、“添加到桌面”或“安装应用”。</li><li>名称建议填写“钳工练习”。</li><li>确认添加。</li></ol><p class="sm tl mt1">Chrome/Edge 打开本地 HTML 时可能只显示“添加到主屏幕”，不会显示完整 PWA 安装，这是正常的。</p></div>';}else{html='<div class="wi"><div class="ct">通用方法</div><ol class="sm" style="padding-left:1.2rem;line-height:1.9"><li>用手机浏览器打开本 HTML 文件。</li><li>打开浏览器菜单或分享菜单。</li><li>查找“添加到主屏幕 / 添加到桌面 / 创建快捷方式”。</li><li>确认添加。</li></ol></div>';}document.getElementById('install-guide').innerHTML=html;}
let bankPage=0;const BANK_PER_PAGE=20;
function goBank(type){document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tc').forEach(x=>x.classList.remove('active'));document.querySelector('[data-tab="bank"]').classList.add('active');document.getElementById('tab-bank').classList.add('active');document.getElementById('bank-type').value=type;document.getElementById('bank-cat').value='all';document.getElementById('bank-search').value='';bankPage=0;renBank();}
function renBank(){const ls=document.getElementById('bank-list');const tp=document.getElementById('bank-type').value,ca=document.getElementById('bank-cat').value,sw=document.getElementById('bank-search').value.trim().toLowerCase();let pool=[];const ts=tp==='all'?['single','multi','judge','short','calc']:[tp];ts.forEach(t=>{if(QB[t])pool=pool.concat(QB[t]);});if(ca!=='all')pool=pool.filter(q=>q.category===ca);if(sw)pool=pool.filter(q=>q.question.toLowerCase().includes(sw));const total=pool.length;const pages=Math.max(1,Math.ceil(total/BANK_PER_PAGE));if(bankPage>=pages)bankPage=pages-1;if(bankPage<0)bankPage=0;const start=bankPage*BANK_PER_PAGE;const slice=pool.slice(start,start+BANK_PER_PAGE);document.getElementById('bank-page-info').textContent=(bankPage+1)+'/'+pages+' (共'+total+'题)';document.getElementById('bank-prev').disabled=bankPage===0;document.getElementById('bank-next').disabled=bankPage>=pages-1;ls.innerHTML='';if(slice.length===0){ls.innerHTML='<p class="ce tl mt2">无匹配题目</p>';return;}slice.forEach(q=>{const d=document.createElement('div');d.className='wi';const tn=q.type==='single'?'单选':q.type==='multi'?'多选':q.type==='judge'?'判断':q.type==='short'?'简答':'计算';let ansHtml='';if(q.type==='single'){ansHtml='<div class="sm mt1"><b>答案：'+q.answer+'</b></div>';if(q.options)Object.entries(q.options).forEach(([k,v])=>{ansHtml+='<div class="sm tl" style="padding-left:1rem">'+k+'. '+v+(k===q.answer?' <span style="color:var(--s)">✓</span>':'')+'</div>';});}else if(q.type==='multi'){ansHtml='<div class="sm mt1"><b>答案：'+q.answer.join('')+'</b></div>';if(q.options)Object.entries(q.options).forEach(([k,v])=>{ansHtml+='<div class="sm tl" style="padding-left:1rem">'+k+'. '+v+(q.answer.includes(k)?' <span style="color:var(--s)">✓</span>':'')+'</div>';});}else if(q.type==='judge'){ansHtml='<div class="sm mt1"><b>答案：'+(q.answer?'正确 (√)':'错误 (×)')+'</b></div>';}else{ansHtml='<div class="sm mt1"><b>参考答案：</b>'+q.answer+'</div>';}d.innerHTML='<div class="qm">['+tn+'] '+(q.category||'')+'</div><div class="qt" style="font-size:0.95rem">'+q.question+'</div>'+ansHtml;ls.appendChild(d);});}
init();

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('./service-worker.js').catch(() => {});
  });
}
